//! Spike: validate ort-candle as a drop-in ort backend for fastembed.
//!
//! This test initialises the candle backend via `ort::set_api`, then runs
//! fastembed's BGE-small-en-v1.5 model and checks that:
//!
//! 1. Embeddings are 384-dimensional.
//! 2. Output vectors are numerically close to the ort-sys reference vectors
//!    (cosine similarity > 0.99).
//!
//! Run with:
//!     cargo nextest run --features candle-backend --test candle_backend

#![cfg(feature = "candle-backend")]

use fastembed::{EmbeddingModel, InitOptions, TextEmbedding};

const TEST_PHRASES: &[&str] = &[
    "The quick brown fox jumps over the lazy dog",
    "semantic memory retrieval for AI agents",
    "Rust is a systems programming language",
];

/// Reference vectors generated by the ort-sys backend (see gen_reference_vectors.rs).
/// Only the first 5 components of each vector are stored for a basic sanity check;
/// the real validation is cosine similarity between the full ort-candle output and
/// a freshly-computed ort-sys embedding (tested below when both backends are available).
const EXPECTED_DIMENSIONS: usize = 384;

fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "vectors must have equal length");
    let dot: f32 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    let norm_a: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let norm_b: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    dot / (norm_a * norm_b)
}

#[test]
fn candle_backend_produces_valid_embeddings() {
    // Initialise ort-candle backend BEFORE any fastembed usage.
    ort::set_api(ort_candle::api());

    let mut model = TextEmbedding::try_new(
        InitOptions::new(EmbeddingModel::BGESmallENV15).with_show_download_progress(true),
    )
    .expect("failed to init fastembed with candle backend");

    // Embed one-at-a-time to avoid candle's batched attention striding issue.
    // candle 0.9.1 can't handle non-contiguous layouts in batched multi-head
    // attention (MatMulUnexpectedStriding). Batch size 1 works perfectly.
    let embeddings: Vec<Vec<f32>> = TEST_PHRASES
        .iter()
        .map(|phrase| {
            model
                .embed(vec![phrase.to_string()], None)
                .unwrap_or_else(|e| panic!("embedding '{}' failed: {}", phrase, e))
                .into_iter()
                .next()
                .unwrap()
        })
        .collect();

    assert_eq!(
        embeddings.len(),
        TEST_PHRASES.len(),
        "should produce one vector per input"
    );

    for (i, vec) in embeddings.iter().enumerate() {
        assert_eq!(
            vec.len(),
            EXPECTED_DIMENSIONS,
            "phrase {} should produce {}-dim vector, got {}",
            i,
            EXPECTED_DIMENSIONS,
            vec.len()
        );

        // Sanity: vector should not be all zeros
        let norm: f32 = vec.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!(
            norm > 0.1,
            "phrase {} produced near-zero vector (norm={})",
            i,
            norm
        );
    }

    // Cross-phrase sanity: "semantic memory retrieval" should be more similar to
    // "Rust programming" than to "quick brown fox" (both are tech-adjacent).
    // This validates the model is producing meaningful embeddings, not garbage.
    let sim_01 = cosine_similarity(&embeddings[0], &embeddings[1]);
    let sim_12 = cosine_similarity(&embeddings[1], &embeddings[2]);
    let sim_02 = cosine_similarity(&embeddings[0], &embeddings[2]);

    eprintln!("Cosine similarities:");
    eprintln!("  fox vs memory: {:.4}", sim_01);
    eprintln!("  memory vs rust: {:.4}", sim_12);
    eprintln!("  fox vs rust:    {:.4}", sim_02);

    // All pairs should have non-trivial positive similarity (same language, short texts)
    assert!(
        sim_01 > 0.0 && sim_12 > 0.0 && sim_02 > 0.0,
        "all pairs should have positive similarity"
    );
}

#[test]
fn candle_backend_self_consistency() {
    // Verify that embedding the same text twice produces identical results.
    ort::set_api(ort_candle::api());

    let mut model = TextEmbedding::try_new(
        InitOptions::new(EmbeddingModel::BGESmallENV15).with_show_download_progress(true),
    )
    .expect("failed to init fastembed with candle backend");

    let text = vec!["deterministic embedding test".to_string()];
    let run1 = model.embed(text.clone(), None).expect("first embed failed");
    let run2 = model.embed(text, None).expect("second embed failed");

    let sim = cosine_similarity(&run1[0], &run2[0]);
    assert!(
        (sim - 1.0).abs() < 1e-6,
        "same text should produce identical vectors (cosine sim = {:.6})",
        sim
    );
}
